config/routes.rb
Rails.application.routes.draw do

    root 'games#index'
    get 'play' => 'games#play'
    get 'statitistics' => 'games#statitistics'
    get 'result' => 'games#result'
    get 'hit' => 'games#hit_or_stand'
    get 'stand' => 'games#hit_or_stand'

end

app/models/game.rb
class Game < ActiveRecord::Base

	CARD_DESCKS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 'J', 'Q', 'K', 'A']*6 #6 Decks

	has_many :steps #each step of the game 

	before_save :game_status #update game score on each step and save result 

	# shuffle card and give to user in first round
	def get_cards
		cards = shuffle_cards
		cards[0..2]
	end

	# check if game completed or not and provide next card to game
	def hit_or_stand(step_type)
		if completed?
			nil
		else	
			step = {step_type: step_type, p_card: '', d_card: '',game_id: self.id}
			step_card = shuffle_cards.last.to_s
			if step_type == 'hit'
				step[:p_card] = step_card
			else
				step[:d_card] = step_card
			end
			Step.create(step)
			step_card
		end	
	end

	#update game status 
	def game_status
		game_result = self.check_result
		self.result = game_result if game_result.present?
	end
		
	#check game result
	def check_result
		if self.d_score == 21 || self.p_score > 21
			'Dealer Win'
		elsif self.p_score == 21 || self.d_score > 21
			'Player Win'
		elsif self.d_score > 16# && self.p_score > 16
			if self.d_score == self.p_score
			  'Match Draw'
			elsif self.d_score > self.p_score 
				'Dealer Win'
			else
			    'Player win'
			end	
		else
			''
		end		
	end	

	#check game completed or not
	def completed?
		self.result.present? ? true : false
	end

	#game result 
	def game_result
		self.result.present? ? self.result : 'No Result'
	end

	#intialize game and first step
	def self.start
		game = Game.create(p_score: 0, d_score: 0, price: 10)
		card = game.get_cards
		game.steps.create(p_card: card[0..1].join(','), d_card: card[2],step_type: 'hit')
		game
	end

	private
	#shuffle cards before giving to game
	def shuffle_cards
		CARD_DESCKS.shuffle.shuffle
	end		
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :game
  before_create :update_game_score

  SCORE = { '2' => 2, '3' => 3, '4' => 4, '5' => 5, '6' => 6, '7' => 7, '8' => 8, '9' => 9, '10' => 10, 'J' => 10, 'Q' => 10,
  			'K' => 10, 'A' => 11, '' => 0, nil => 0
  		}

  #update game score on each step
  def update_game_score
  	game = self.game
  	game.d_score = game.d_score + get_score(d_card)
  	game.p_score = game.p_score + get_score(p_card)
  	game.save
  end

  def player_cards
  	self.p_card.split(',')
  end
  
  def dealer_cards
  	self.d_card.split(',')
  end	

  private
  #getting player and dealer score from SCORE constant
  def get_score(cards)
  	cards = cards.to_s.split(',')
  	(cards.size == 1) ? SCORE[cards[0]] : SCORE[cards[0]] + SCORE[cards[1]]
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index   
  end

  def play
  	@game = Game.start
  	@game_step = @game.steps.first
  end

  def hit_or_stand
  	@game = Game.find(params[:id])
    @step_type = params[:step_type]
    @card = @game.hit_or_stand(@step_type)
    @game.reload
    @game_completed = @game.completed?
  end

  def result
  end  

  def statitistics
     @games = Game.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/hit_or_stand.js.erb
<% if @card.present? %>
	
	var game_status = <%= @game_completed %>;
	var step_type   = "<%= @step_type %>";
	var result      = "<%= @game.result %>";
	
	$("div#"+step_type).append('<%= link_to @card, "#",:class=>"button button-primary button-box button-large" %>');
	$('#p_score').text("<%= @game.p_score %>");
	$('#d_score').text("<%= @game.d_score %>");

	if (game_status){
		game_over(result);
	}else if(step_type == 'stand'){
		game_stand();
	}

<% end %>

app/views/games/index.html.erb
<div class='cl-md-9'>
	<div class='row margin-top-40'>
		<div class='cl-sm-6 cl-md-6 pull-left'>
			<div class='row'>
				<div class='cl-md-12 margin-bot-40'>
					<%= link_to 'PLAYER',"#",:class=>'button button-primary button-rounded button-jumbo' %>
				</div>
			</div>
		</div>
		<div class='cl-sm-6 cl-md-6 pull-right'>
			<div class='row'>
				<div class='cl-md-12 margin-bot-40'>
					<%= link_to 'DEALER',"#",:class=>'button button-royal button-rounded button-jumbo' %>
				</div>
			</div>
		</div>
	</div>
	<center>
      <%= link_to 'Deal', play_path,:class=> 'button button-3d button-action button-pill' %>
    </center>
</div>

app/views/games/play.html.erb
<div class='row margin-top-40'>
	<div class='cl-sm-6 cl-md-6 pull-left'>
		<div class='row'>
			<div class='row'>
				<div class='cl-md-12 margin-bot-40'>
					<%= link_to 'PLAYER',"#",:class=>'button button-primary button-rounded button-jumbo' %>
				</div>
			</div>
			<div class='row'>
				<div class='cl-md-12 margin-bot-40'>
					<%= link_to "Score","#",:class=>'button button-3d button-action button-pill' %>
					<button class="button button-glow button-circle button-action button-jumbo" id='p_score'>
					    <%= @game.p_score%>
				    </button>
				</div>
			</div>
			<div class='row'>
				<div class='cl-md-12 margin-right-10' id="hit">
					<% @game_step.player_cards.each do |f| %>
						<%= link_to f, "#",:class=>'button button-primary button-box button-large' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class='cl-sm-6 cl-md-6 pull-right'>
		<div class='row'>
			<div class='row'>
				<div class='cl-md-12 margin-bot-40 pull-left'>
					<%= link_to 'DEALER',"#",:class=>'button button-royal button-rounded button-jumbo' %>
				</div>
			</div>
			<div class='row'>	
				<div class='cl-md-12 margin-bot-40'>
					<button class="button button-glow button-circle button-action button-jumbo" id='d_score'>
					    <%= @game.d_score%>
				    </button>
				    <%= link_to "Score","#",:class=>'button button-3d button-action button-pill' %>
				</div>
			</div>
			<div class='row'>	
				<div class='cl-md-12 margin-right-10 pull-left' id="stand">
					<% @game_step.dealer_cards.each do |f| %>
						<%= link_to f, "#",:class=>'button button-primary button-box button-large' %>
					<% end %>
				</div>
			</div>	
		</div>
	</div>
</div>
<div class="row margin-top-40">
	<div class="cl-sm-12 cl-md-12">
		<center>
			<%= link_to "Hit", hit_path(id: @game.id, step_type: 'hit'), remote: true,:class=>'button button-glow button-rounded button-caution', id: 'hit_button' %>
			<%= link_to "Stand", stand_path(id: @game.id, step_type: 'stand'), remote: true, :class=>'button button-glow button-rounded button-highlight', id: 'stand_button' %>
		</center>
	</div>
</div>

<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog modal-lg">
	  <div class="modal-content">
	    <div class="row margin-top-40 margin-bot-40">
	      <div class="cl-sm-12 cl-md-12">
	        <div class="cl-sm-12 cl-md-12">
	          <center>
	            <%= link_to @game.result,"javascript:void(0);",:class=>'button button-glow button-rounded button-caution margin-right-20' ,id: 'winner_text' %>
	          </center>
	        </div>
	      </div>
	      <div class="cl-sm-12 cl-md-12 margin-top-40">
	        <center>
	          <%= link_to 'PLAY AGAIN', root_path,:class=>'button button-royal button-rounded button-jumbo margin-right-20' %>
	          <%= link_to 'STATISTICS', statitistics_path ,:class=>'button button-royal button-rounded button-jumbo' %>
	        </center>
	      </div>
	    </div>
	  </div>
	</div>
</div>

<script type="text/javascript">
    $('#myModal').on('hidden.bs.modal', function (e) {
  		window.location= "<%= root_url %>";
	});
    <% if @game.result.present? %>
		game_over("<%= @game.result %>");
	<% end %>	
</script>

app/views/games/result.html.erb
<div class="row margin-top-40">
	<div class="cl-sm-12 cl-md-12">
		<div class="cl-sm-12 cl-md-12">
			<center>
				<%= link_to 'Player Wins!',"#",:class=>'button button-glow button-rounded button-caution margin-right-20' %>
			</center>
		</div>
	</div>
	<div class="cl-sm-12 cl-md-12 margin-top-40">
		<center>
			<%= link_to 'DEAL AGAIN',"#",:class=>'button button-royal button-rounded button-jumbo margin-right-20' %>
			<%= link_to 'STATISTICS',"#",:class=>'button button-royal button-rounded button-jumbo' %>
		</center>
	</div>
</div>

app/views/games/statitistics.html.erb
<div class="row">
	<p><center><h2>STATISTICS</h2></center></p>
	<div class="cl-sm-12 cl-md-12">
		<table class="table table-condensed">
		    <thead>
		      <tr>
		        <th>Game No.</th>
		        <th>Player</th>
		        <th>Dealer</th>
		        <th>Result</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<% @games.each_with_index do |f, index| %>
			      <tr>
			        <td><%= index %></td>
			        <td><%= f.p_score %></td>
			        <td><%= f.d_score %></td>
			        <td><%= f.game_result %></td>
			      </tr>
			    <% end %>
		    </tbody>
		</table>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>BlackJack</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, intial-scale=1, maximum-scale=1">
	  <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:700' rel='stylesheet' type='text/css'>
      <link href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">
	</head>
	<body>
		<nav class="navbar navbar-inverse">
            <div class="container-fluid">
			    <div class="navbar-header">
			    	<a class="navbar-brand" href="<%= root_path %>">Black Jack</a>
			    </div>
    		<div>
		</nav>
		<div class="container" >
			<% flash.each do | name , msg| %>
      			<%= content_tag(:div, msg, class:"alert alert-info") %>
  			<% end %>
			<div class='row margin-top-100 margin-rl-200'>
				<%= yield %>
			</div>
		</div>	
	</body>
</html>